version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"  # React app will be accessible at http://localhost:8080

  backend:
    build: ./backend
    ports:
      - "3000:3000"  # Backend API will be accessible at http://localhost:3000

