services:
  cloudflare-dns-manager:
    image: ghcr.io/jas0n0ss/cloudflare-dns-manager:latest
    container_name: cloudflare-dns-manager
    ports:
      - "8080:8080"
    environment:
      - PUBLIC_IP_POLL_RATE_SEC=90
    volumes:
      - ./db:/app/db
    restart: unless-stopped  # This ensures the container restarts unless manually stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]  # Using the root path (/) for health check
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
